name: Sweep external PRs
on:
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  sweep:
    runs-on: ubuntu-latest
    steps:
      - name: Close all open PRs from non-members
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            let page = 1, closed = 0;

            while (true) {
              const pulls = await github.rest.pulls.list({
                owner, repo, state: 'open', per_page: 100, page
              });
              if (pulls.data.length === 0) break;

              for (const pr of pulls.data) {
                const assoc = pr.author_association;
                if (!['OWNER','MEMBER','COLLABORATOR'].includes(assoc)) {
                  await github.rest.issues.createComment({
                    owner, repo, issue_number: pr.number,
                    body: "Thanks for the PR! This is a course project and we aren’t accepting external contributions."
                  });
                  await github.rest.pulls.update({
                    owner, repo, pull_number: pr.number, state: 'closed'
                  });
                  closed++;
                }
              }
              page++;
            }

            core.notice(`Closed ${closed} PR(s).`);
