name: CI/CD Pipeline (Dev Cluster)
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  IMAGE_NAME: svc-courses
  RELEASE_NAME: svc-courses-dev
  IMAGE_PLATFORMS: linux/amd64
  K8S_NAMESPACE: rso
  VALUES_FILE: ./helm/environments/values-dev.yaml
  

jobs:
  # TODO: Unit tests

  build:
    name: Build and Push Docker Image
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      image_name: $IMAGE_NAME
      image_platforms: $IMAGE_PLATFORMS

  deploy-dev:
    name: Deploy to Dev AKS Cluster
    needs: build
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      image_tag: ${{ needs.build.outputs.image_tag }}
      release_name: $RELEASE_NAME
      k8s_namespace: $K8S_NAMESPACE
      values_file: $VALUES_FILE
      app_version: ${{ github.sha }}

  # TODO: Smoke tests on dev deployment
