name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'The image tag to deploy'
        required: true
        type: string

permissions:
  contents: read
  id-token: write

env:
  # TODO: Move to inputs
  K8S_NAMESPACE: rso
  IMAGE_TAG: ${{ inputs.image_tag }}

jobs:
  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login (OIDC)
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Fetch AKS Config from Key Vault
      run: |
        fetch_secret() {
          az keyvault secret show \
            --vault-name ${{ vars.KEYVAULT_NAME }} \
            --name "$1" \
            --query value -o tsv
        }

        echo "RESOURCE_GROUP_NAME=$(fetch_secret rg-name)" >> $GITHUB_ENV
        echo "AKS_CLUSTER_NAME=$(fetch_secret aks-name)" >> $GITHUB_ENV

    - name: Authenticate to AKS
      run: |
        az aks get-credentials \
          --resource-group "$RESOURCE_GROUP_NAME" \
          --name "$AKS_CLUSTER_NAME" \
          --overwrite-existing

    - name: Deploy to AKS using Helm
      run: |
        helm upgrade --install svc-courses ./helm \
          --namespace $K8S_NAMESPACE \
          --values ./helm/values.yaml \
          --values ./helm/environments/values-dev.yaml \
          --set image="$IMAGE_TAG"
